### ISSUE TITLE
Some questions about missing tiles and other things..

### ISSUE THREAD

**Issue by adam-ce** [felixpalmer/procedural-gl-js#38] opened 2021-10-13 13:54 UTC
Hi,
I'm from TU Wien and we got our hands on some high resolution height data for Austria, and now we are playing around with it and with your 3d map. We are thinking of it as a possible research vehicle, and tool for mountaineers. 

First of all, we are having some troubles: https://www.youtube.com/watch?v=3q-_05H2HpU
- Some photo tiles are missing
- some DEM tiles are also missing.

Our dem tiles have a resolution of 256x256, so we had to change that. we also increased the maxZoom for dem tiles to 20 i think. I don't know whether that has something to do with the problem. In any case, we are willing to put in work, but maybe you could give us some pointers? We have background in 3d, but not so much in java script yet.

Also another thing: it's likely we'll put one or several students onto some tasks. Are you still actively developing this project? Would you like to receive merge request? co-supervise or something? if you like we can also have a zoom meeting, if you moved on, that's also fine :)

Cheers, Adam

**Comment by felixpalmer** [comment] 2021-10-18 07:55
Could you share a live example, e.g. on a jsfiddle or similar? From your video it isn't possible to tell where the problem is. There is good chance the issue is not with the client library, but with your tile server.

I have been a bit pressed for time lately, but I do plan on developing the project going forward. Would be happy to discuss, could you reach out via Twitter?

**Comment by adam-ce** [comment] 2021-10-20 15:21
hi,
the tile server was working fine. besides, the app should show old tiles, instead of a white void. i think it is an issue with the tile cache.

but any way, we found cesium.  the documentation is way better, the project is more mature, supports quantised mesh tiles, and doesn't have this bug. there are other bugs (for instance our massive dataset causes some unnecessary slowness), but these should be easier to pinpoint and fix.

so thanks, sorry, and cheers.
Adam

**Comment by felixpalmer** [comment] 2021-10-26 14:38
Closing due to lack of useful debug info

**Closed as completed by felixpalmer** 2021-10-26 14:38 UTC
