### ISSUE TITLE
Map fails to load properly when latitude is above 61°N

### ISSUE THREAD

**Issue by flother** [felixpalmer/procedural-gl-js#4] opened 2020-11-30 10:19 UTC
Procedural GL JS looks to be a really interesting library, thanks for making it.

When you create a map that's centred on a location higher than 61°N, the map fails to work as expected. While there's no error in the browser console, neither the elevation data nor the satellite imagery looks like it's loaded properly. Interaction is broken too. This affects all of Iceland plus large parts of Norway, Sweden, Finland, Russia, Canada, and the United States (Alaska).

I've put a [minimal failing example on JSFiddle](https://jsfiddle.net/ygmaz6es/) (line 22 of the Javascript: toggle the latitude between 61.0 and 61.1 to see the map work or fail). You can also see this bug in [the demo](https://felixpalmer.github.io/procedural-gl-js/) by searching for Gjøvik (~60°N, works) or Lillehammer (~61°N, fails), both in Norway.

**Comment by felixpalmer** [comment] 2020-11-30 17:25
Yes you are correct, unfortunately the source NASADEM dataset used on nasadem.xyz only covers all land between 60° N and 56° S latitude. Sorry I know this is annoying for you and I would love to support those countries as there is incredible terrain there, but as this is not a bug with the library itself, but rather the datasource I'm going to close the issue.

**Closed by felixpalmer** 2020-11-30 17:25 UTC

**Comment by tuukka** [comment] 2020-11-30 17:33
Would it be possible to get an error message explaining the situation?

**Comment by flother** [comment] 2020-12-01 12:59
I _knew_ there was a reason I'd not used the NASADEM data before ;)

I hope you don't mind if I carry on the conversation even though the issue is closed. There's some good news: [ArcticDEM](https://www.pgc.umn.edu/data/arcticdem/) provides a freely-available two-metre resolution DEM for all land north of 60°N. Would you be interested in adding that to [nasadem.xyz](https://www.nasadem.xyz/)?

Browsing through the Procedural GL code, I saw that the library is tightly linked to nasadem.xyz — for example, as far as I can see it's the [only supported elevation source](https://github.com/felixpalmer/procedural-gl-js/blob/76d9aa845a341e0b0e5d39be5b0ac3c8656a439d/src/datasources/elevation.js). That's fine of course, it's your prerogative. But would you be interested in broadening support? I have my own elevation data in [Mapbox Terrain-RGB format](https://blog.mapbox.com/global-elevation-data-6689f1d0ba65), which is slightly different to the nasadem.xyz format. I'd love to use that with Procedural GL.

(I wish I could promise that I could help with this if you like the idea. I _might_ be able to help, but that's the best I can offer.)

**Comment by felixpalmer** [comment] 2020-12-01 13:44
Well, I can't deny ArcticDEM appears to be a good compliment to NASADEM, so I will certainly consider adding it to nasadem.xyz. Can't make any promises on when though! Could you let me know what your use case is? Naturally if it were something that would get good publicity then it would bump the priority of doing the data update.

As for supporting other elevation formats, then at the moment I'd like to just stick with the built-in elevation datasource as it keeps things simple, and while NASADEM.xyz doesn't have coverage above 60N then otherwise it is pretty solid. Also the mapbox encoding is less efficient to decode as with the nasadem.xyz format the 2 channels encode a 16-bit integer. All that said, the source code is open so you should be able to modify it for use with your own data.

@tuukka I'll add an error message at any rate

**Comment by flother** [comment] 2020-12-02 09:56
I work for an Icelandic company that's, very roughly, a local competitor to Google Maps. I'm the programmer/cartographer in charge of our map at [ja.is/kort](https://en.ja.is/kort/?x=361228&y=413283&nz=10). It's 2.5D, but I'm always on the lookout for something that would allow us to also have a 3D terrain map with a label overlay. That's where my interest in Procedural GL comes from — the only problem being that Iceland is above 63°N.

The idea for Já having a 3D map is still just that, an idea, so I wouldn't want you to go out of your way to add ArcticDEM to nasadem.xyz on my behalf. But if the elevation data were there and the satellite imagery for Iceland was good, I would definitely make the case internally for doing something with it.
