### ISSUE TITLE
Something is worng with elevation data

### ISSUE THREAD

**Issue by gena** [felixpalmer/procedural-gl-js#2] opened 2020-11-21 19:19 UTC
The elevation is broken in all examples running on Win 10, 2080GPU, tried both chrome and firefox.
![image](https://user-images.githubusercontent.com/169821/99885624-b87d2f00-2c36-11eb-8d69-aef3314edabd.png)

**Comment by felixpalmer** [comment] 2020-11-22 14:49
Thanks for the report. Could you paste the output you get from https://webglreport.com/?

**Comment by gena** [comment] 2020-11-22 16:06
![image](https://user-images.githubusercontent.com/169821/99908789-def9a380-2ce4-11eb-8ef8-3697b0b961bb.png)


```

WebGL 2 Functions Implementation Status:
--
  | 88 of 88 new functions implemented.
  | copyBufferSubData
  | getBufferSubData
  | blitFramebuffer
  | framebufferTextureLayer
  | getInternalformatParameter
  | invalidateFramebuffer
  | invalidateSubFramebuffer
  | readBuffer
  | renderbufferStorageMultisample
  | texStorage2D
  | texStorage3D
  | texImage3D
  | texSubImage3D
  | copyTexSubImage3D
  | compressedTexImage3D
  | compressedTexSubImage3D
  | getFragDataLocation
  | uniform1ui
  | uniform2ui
  | uniform3ui
  | uniform4ui
  | uniform1uiv
  | uniform2uiv
  | uniform3uiv
  | uniform4uiv
  | uniformMatrix2x3fv
  | uniformMatrix3x2fv
  | uniformMatrix2x4fv
  | uniformMatrix4x2fv
  | uniformMatrix3x4fv
  | uniformMatrix4x3fv
  | vertexAttribI4i
  | vertexAttribI4iv
  | vertexAttribI4ui
  | vertexAttribI4uiv
  | vertexAttribIPointer
  | vertexAttribDivisor
  | drawArraysInstanced
  | drawElementsInstanced
  | drawRangeElements
  | drawBuffers
  | clearBufferiv
  | clearBufferuiv
  | clearBufferfv
  | clearBufferfi
  | createQuery
  | deleteQuery
  | isQuery
  | beginQuery
  | endQuery
  | getQuery
  | getQueryParameter
  | createSampler
  | deleteSampler
  | isSampler
  | bindSampler
  | samplerParameteri
  | samplerParameterf
  | getSamplerParameter
  | fenceSync
  | isSync
  | deleteSync
  | clientWaitSync
  | waitSync
  | getSyncParameter
  | createTransformFeedback
  | deleteTransformFeedback
  | isTransformFeedback
  | bindTransformFeedback
  | beginTransformFeedback
  | endTransformFeedback
  | transformFeedbackVaryings
  | getTransformFeedbackVarying
  | pauseTransformFeedback
  | resumeTransformFeedback
  | bindBufferBase
  | bindBufferRange
  | getIndexedParameter
  | getUniformIndices
  | getActiveUniforms
  | getUniformBlockIndex
  | getActiveUniformBlockParameter
  | getActiveUniformBlockName
  | uniformBlockBinding
  | createVertexArray
  | deleteVertexArray
  | isVertexArray


```

**Comment by tdurand** [comment] 2020-11-25 11:28
I have the same problem with Windows 10 : Chrome and firefox .. but when I try with Ubuntu and chromium it works fine.

BTW 🎉🎉 for releasing this.. I have been following your work with procedural.eu the past years ;-)

**Comment by felixpalmer** [comment] 2020-11-25 13:20
Unfortunately I don't have a Windows 10 machine to test on, but I do have a theory about why this is happening. Could you try and see if the problem persists when you add the `interpolateFloat` GET parameter? E.g. https://felixpalmer.github.io/procedural-gl-js/?interpolateFloat

**Comment by tdurand** [comment] 2020-11-25 13:51
The problem seems to be the same.. let me know if I can do another test (can be pulling the repo and changing a few things in the code also if you need to)

**Comment by felixpalmer** [comment] 2020-11-30 17:51
@tdurand thanks for the offer, I don't have any other obvious suggestion, debugging these issues can be difficult as GPUs are black boxes and it is hard to know what exactly is going wrong. Add to this the fact that this is going through ANGLE and the debugging process can be "fun" (e.g. https://stackoverflow.com/questions/27348125/colors-output-from-webgl-fragment-shader-differ-significantly-across-platforms)

The terrain lookup is done via two (dependent) texture lookups, see `shaders/getHeight.glsl` and `shaders/readTexVirtual.glsl` for details. One thing to notice is the manual bilateral filtering that is done in `shaders/readTexVirtual.glsl`. My best guess would be that the issue is somewhere in this code, so if this code makes sense to you, you could try playing around with it and see if anything "interesting" happens. Things I would try:

- Change the precision of variables to be `highp` everywhere
- Check if the terrain at least somewhat resembles the source data (i.e. are the spikes bigger if looking at mountains, and don't appear when in a flat area)
- Change the return value of `getHeight` to something to a smooth function, e.g.:
  - `return 1000.0 * sin( 25.0 * scaledUv.x )` (should give smooth waves across the terrain)
  - `return 1000.0 * sin( 25.0 * scaledUv.x * index )`  (should give smooth waves across the terrain, with frequency depending on terrain tile used)

**Comment by tdurand** [comment] 2020-11-30 19:40
I see.. yes I think the best way for you would be to gets your hand on a machine  running windows 10 and reproduce the problem (not sure actually if it happens on every windows machine ?)

I did tried

- `highp` on the shaders you mentionned .. doesn't seem to change
- no, for example see in Paris, supposed to be relatively flat and the bug is not dependent to the elevation
![Screenshot_2020-11-30 Procedural GL JS](https://user-images.githubusercontent.com/533590/100654911-cde70d00-334a-11eb-9e82-18461fffc28d.jpg)
- I did try to return a custom value in the `getHeight` shader .. but it doesn't seem to change much.. not sure also if I do right the dev worflow.. I'm running `npm run dev` everytime I make a change but didn't verify it picks the last build...

**Comment by felixpalmer** [comment] 2020-11-30 23:37
Well, Paris does look a lot flatter than the image posted by gena.

As for the dev flow, changing the value in `getHeight` should be very noticeable. Running `npm run dev` is probably not going to work on Windows, try `npm run build-dev` and then be sure to open the `index.module.html` file (as this will include the dev build. But yes, you are right it is likely best if I try it on a Windows machine myself

**Comment by gena** [comment] 2020-11-30 23:50
Just tried ```npm run build-dev``` with ```index.module.html``` - no luck, similar errors, looks indeed as some compatibility issue.

**Comment by tdurand** [comment] 2020-12-01 09:58
Yes I wasn't getting the updated results.. now using `index.module.html` after a `npm run build-dev` and it does reflects the changes in the code:

- `highp` in the getHeight shader  : don't think it changes much

![highp](https://user-images.githubusercontent.com/533590/100724662-68833280-33c3-11eb-87be-a81e0fd9534a.jpg)

- `return 1000.0 * sin( 25.0 * scaledUv.x )`  

zoomed in
![smoothwave](https://user-images.githubusercontent.com/533590/100724719-7afd6c00-33c3-11eb-98ee-7eba6b73b047.jpg)

- `return 1000.0 * sin( 25.0 * scaledUv.x * index )`

zoomed in
![smoothwaweindex](https://user-images.githubusercontent.com/533590/100724786-8cdf0f00-33c3-11eb-9a00-0f9cd6c76900.jpg)

zoom out
![smoothwaweindexzoomout](https://user-images.githubusercontent.com/533590/100724790-8e103c00-33c3-11eb-9309-17470dd0666f.jpg)

From what I understand.. the general elevation value is respected.. but it does this staircase things on zoom in .. the `highp` doesn't fix it

Hope this is helpful + yes I guess next step is for you to get your hands on a windows 10 laptop... 

Happy to help with further test !

Thibault

**Comment by felixpalmer** [comment] 2020-12-01 11:34
@tdurand OK that is surprising, but does seem to narrow down the issue. I was expecting those sin curves to come out smooth. I tried launching a Window VM via BrowserStack but it didn't work. Would you mind also trying the following alternative return statements:

- `return 1000.0 * sin( 25.0 * 1024.0 * indirectionUv.x );`
- `return 1000.0 * sin( 32.0 * tile.x );`
- `return 1000.0 * sin( 0.001 * p.x );`

**Comment by tdurand** [comment] 2020-12-01 14:03
All of them seem to come out smooth , I must admit I don't understand why 😁 , but 👍

 `return 1000.0 * sin( 25.0 * 1024.0 * indirectionUv.x );`

![1test](https://user-images.githubusercontent.com/533590/100750003-bad54b00-33e5-11eb-8a20-8ea10109b49b.jpg)

`return 1000.0 * sin( 32.0 * tile.x );`

![2test](https://user-images.githubusercontent.com/533590/100750009-bc9f0e80-33e5-11eb-99a0-176b20341b59.jpg)

 `return 1000.0 * sin( 0.001 * p.x );`

![3test](https://user-images.githubusercontent.com/533590/100750040-c3c61c80-33e5-11eb-833c-16269bff7ce0.jpg)

**Comment by Pomax** [comment] 2020-12-02 16:05
Note that windows 10 is technically entirely free to use (you just can't customize it until you activate it), so you should be able to just grab the installer and set up a dual boot if you want to better test this.

**Comment by felixpalmer** [comment] 2020-12-03 14:26
I managed to reproduce the bug and pushed a fix in https://github.com/felixpalmer/procedural-gl-js/pull/5

@gena @tdurand could you try and see if this resolves the issue for you?

**Comment by tdurand** [comment] 2020-12-03 18:59
Fixed !

**Closed** 2020-12-07 09:26 UTC
Labels: bug
